meetings:
- AI制度研究会
- AI時代における自動運転車の社会的ルールの在り方検討サブワーキンググループ
- Beyond 5Gに向けた研究開発・国際標準化に関する検討会
- Connected Industries推進のための協調領域データ共有・AIシステム開発促進事業に係る実施体制の決定について
- DX支援ガイダンス
- EBPM推進委員会幹事会（廃止）
- EBPM推進委員会（廃止）
- G20グローバル・スマートシティ・アライアンス
- GビズIDの委任機能に関する検討会
- Peppolに関する会議
- RegTechコンソーシアム
- Verifiable Credential (VCVDC) の活用におけるガバナンスに関する有識者会議
- Web3.0研究会
- 「デジタルの日」検討委員会
- 「モビリティ・ロードマップ」のありかたに関する研究会
- こどもに関する情報・データ連携 副大臣プロジェクトチーム
- コンプライアンス委員会
- サービスデザイン関連ガイドライン改訂に係る検討会
- ゼロトラストアーキテクチャに関する検討会
- テクノロジーベースの規制改革推進委員会
- デジタルガーデンシティ国家とウェルビーイングに関するワークショップ
- デジタルマーケットプレイスに関する検討会
- デジタル・ガバメント推進標準ガイドライン改定検討会
- デジタル交通社会のありかたに関する研究会
- デジタル庁情報システム調達改革検討会
- デジタル技術を活用した酒類・たばこ年齢確認ガイドライン
- デジタル改革に向けたマルチステークホルダーモデルの運用（処分通知等のデジタル化）
- デジタル田園都市国家研究投資制度に関する会議
- デジタル社会推進会議
- デジタル社会推進会議幹事会
- デジタル社会推進実践ガイドブック DS-500
- デジタル社会構想会議
- デジタル臨時行政調査会作業部会 テクノロジーベースの規制改革推進委員会（廃止）
- デジタル臨時行政調査会作業部会 法制事務のデジタル化検討チーム（廃止）
- デジタル臨時行政調査会作業部会(廃止)
- デジタル臨時行政調査会作業部会（廃止）
- デジタル臨時行政調査会第9回作業部会
- デジタル臨時行政調査会（廃止）
- デジタル関係制度改革検討会
- デジタル関係制度改革検討会 テクノロジーベースの規制改革推進委員会
- デジタル関係制度改革検討会 デジタル法制ワーキンググループ（廃止）
- データセキュリティワーキンググループ
- データ戦略推進ワーキンググループ
- トラストを確保したDX推進サブワーキンググループ
- トラストを確保したDX推進サブワーキンググループ（廃止）
- ドメイン管理ガイドラインの改定に関する検討会
- フロン排出抑制法に関する検討会
- プラットフォームにおけるデータ取扱いルールの実装に関するサブワーキンググループ（廃止）
- ベース・レジストリ推進有識者会合
- マイナンバーカードと健康保険証の一体化に関する検討会
- マイナンバーカードと健康保険証の一体化に関する検討会 専門家ワーキンググループ
- マイナンバーカードの普及と健康保険証利用に関する関係府省庁会議
- マイナンバーカードの普及・利用の推進に関する関係省庁連絡会議
- マイナンバーカードの機能のスマートフォン搭載に関する検討会
- マイナンバー制度及び国と地方のデジタル基盤抜本改善ワーキンググループ
- マイナンバー情報総点検本部
- マイナンバー法に関する検討会
- モビリティワーキンググループ
- 不動産登記データ連携に関する検討会
- 主任無線従事者制度に関する検討会
- 事業者のデジタル化等に係る関係省庁等連絡会議
- 事業者向けの補助金の電子化及び行政手続の悉皆調査
- 人事業務プロセスに関する検討会
- 公共データ利用規約(仮称)(第1.0 版)に関する検討会
- 利用計画書等に関する会議名不明
- 加古川市の取組
- 加古川市市民意識調査
- 司法試験・司法試験予備試験のデジタル化に関する検討会
- 国・地方ネットワークの将来像及び実現シナリオに関する検討会
- 国家公務員旅費制度見直し検討会
- 国際データガバナンスアドバイザリー委員会
- 国際データガバナンス検討会
- 国際的なデータ流通と利活用に向けて
- 地域幸福度指標の活用促進に関する検討会
- 地域幸福度（Well-Being）指標の活用促進に関する検討会
- 地方公共団体の基幹業務システムの統一・標準化に関する共通機能等技術要件検討会
- 地方公共団体の基幹業務システムの統一・標準化に関する共通機能等技術要件検討会 データ連携ワーキングチーム
- 地方公共団体の基幹業務システムの統一・標準化に関する共通機能等技術要件検討会 宛名管理ワーキングチーム
- 地方公共団体の基幹業務システムの統一・標準化に関する共通機能等技術要件検討会 申請管理ワーキングチーム
- 地方公共団体の基幹業務システムの統一・標準化に関する共通機能等課題検討会
- 地方公共団体の基幹業務等システムの統一・標準化に関する関係省庁会議
- 地方公共団体情報システムにおける文字の標準化に関する有識者会議
- 地方公共団体情報システムにおける文字要件の運用に関する検討会
- 地方公共団体情報システムにおける標準化にかかる共通基準に関する検討会
- 山古志住民会議
- 建築物等の中間・完了検査に関する検討会
- 建設業許可標識等の掲示におけるデジタルサイネージの活用に関する検討会
- 意見書
- 技術検討会議
- 政策評価審議会
- 教育分野の認証基盤の在り方に関する検討会
- 旅行業務取扱管理者関連会議
- 本人確認ガイドラインの改定に向けた有識者会議
- 東京都のスタートアップ戦略に関する検討会
- 構想会議
- 標準仕様の指定都市における課題等検討会
- 横瀬町の概要
- 次世代セキュリティアーキテクチャ検討会
- 次期個人番号カードタスクフォース
- 水道関連法令に基づく検討会
- 河川・ダム管理における新技術導入に関する研究会
- 法の世界のDXを考える法情報実務セミナー2022
- 海外調査項目に関する調査会議
- 温泉法関連検討会
- 神戸市イノベーション創出の取組
- 経由調査に関する業務の実態把握
- 継続検討リスト
- 行政手続法に基づく意見公募手続に関する会議
- 行政研究会議
- 諸外国の法制事務のデジタル化に関する調査・研究
- 道路インフラメンテナンスに関する検討会
- 電子委任状法施行状況検討会
- 電子署名法認定基準のモダナイズ検討会
- 食品衛生法に基づく衛生管理基準に関する検討会
